# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/polytech2024
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.gha
        push: true
        tags: rg.fr-par.scw.cloud/polytech2024/vbenji/back:v1

    - name: Use CLI
      uses: scaleway/action-scw@v0
      with:
        args: container container create name=vbenji-back namespace-id=4f8c01c3-6c86-4cba-abf7-a652eeaa04be registry-image=rg.fr-par.scw.cloud/polytech2024/vbenji/back:v1 min-scale=1 max-scale=1 memory-limit=512 cpu-limit=280 environment-variables.DATASOURCE_URL=jdbc:postgresql://51.159.112.97:27458/etudiant0 environment-variables.S3_HOSTNAME=https://polytech-2024-bucket.s3.fr-par.scw.cloud
        access-key: ${{ secrets.SCW_ACCESS_KEY }}
        secret-key: ${{ secrets.SCW_SECRET_KEY }}
        default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
        default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
